gitIntegration: myGithub
gitRepositoryPath: RjSH1/Swampup2021-su204-cicd-deep-dive  # replace jfrog with your username or org name
artifactoryIntegration: myArtifactory
imageName: app_docker_image
artifactoryUrl: https://icarus1aa.jfrogdev.org   # replace swampup with your server name
sourceRepository: docker-staging-local  # create local repository in Artifactory
prodRepository: docker-prod-local # create local repository in Artifactory
